DROP TABLE IF EXISTS "list_lists" CASCADE;
DROP TABLE IF EXISTS "user_lists" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "lists" CASCADE;
DROP TYPE IF EXISTS "public"."enum_lists_status";

CREATE TABLE IF NOT EXISTS "users"
  ("id" CHAR(36) NOT NULL UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"));


CREATE TYPE "public"."enum_lists_status" AS ENUM('NOT_STARTED', 'STARTED', 'COMPLETED');


CREATE TABLE IF NOT EXISTS "lists"
    ("id" CHAR(36) NOT NULL UNIQUE,
    "name" VARCHAR(255) NOT NULL,
    "status" "public"."enum_lists_status" DEFAULT 'NOT_STARTED',
    "last_status_update" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "is_default" BOOLEAN DEFAULT false,
    "is_parent" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "author_id" CHAR(36) REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "user_lists"
  ("user_id" CHAR(36) NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "list_id" CHAR(36) NOT NULL REFERENCES "lists" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  -- "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("user_id","list_id"));


CREATE TABLE IF NOT EXISTS "list_lists"
  ("child_id" CHAR(36) NOT NULL REFERENCES "lists" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "parent_id" CHAR(36) NOT NULL REFERENCES "lists" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  -- "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("child_id","parent_id"));