import React from "react";
import Head from "next/head";
import styles from "~/styles/Home.module.css";
import { Typography } from "antd";
const { Title, Text } = Typography;

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title>Todo</Title>
        <Text>Welcome to TODO</Text>
      </main>
    </div>
  );
}

export default Home;
