import React from "react";
import Head from "next/head";
import styles from "~/styles/Home.module.css";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Welcome to TODO</h3>
      </main>
    </div>
  );
}

export default Home;
