import Head from "next/head";
import styles from "~/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0";
import Lists from "~/components/Lists";

export default function Home() {
  const { user } = useUser();
  console.log("USER", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Welcome to TODO</h3>
        {user && <Lists user={user} />}
      </main>
    </div>
  );
}
