import Head from "next/head";
import styles from "~/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0";
import { CreateList, ListTable } from "~/components/Lists";
import { Typography } from "antd";
const { Title } = Typography;

export default function Home() {
  const { user } = useUser();

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title level={4}>Lists</Title>
        <CreateList user={user} />
        <ListTable user={user} />
      </main>
    </div>
  );
}
